### ISSUE TITLE
bower  ECONFLICT Unable to find suitable version for webcomponentsjs

### ISSUE THREAD

**Issue by lamjar** [francoischalifour/betisier-iut#1]
I tried to install your project and followed the instructions mentioned in readme But I got this error:

`bower                                      ECONFLICT Unable to find suitable version for webcomponentsjs
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! betisier-iut@1.0.0 postinstall: "bower install"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the betisier-iut@1.0.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the betisier-iut package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs betisier-iut
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls betisier-iut
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\betisier-iut\npm-debug.log`
Can you help me to fix this problem.
I used node v 4.4.4 and bower 1.7.9 and npm 2.15.1

**Comment by francoischalifour** [comment]
I'm not sure what's your purpose of running this project, as it was made for my previous school.

This app uses Polymer 0.5, which is now deprecated. I'm also concerned about the quality of the code.

I, therefore, advise you to search for another similar project on GitHub if you're looking for an app using Node / Handlebars / Polymer all together.

Please let me know if I've misunderstood your point.

**Comment by lamjar** [comment]
thanks Francois ; i would create an web application using NodeJs,Polymer and MySQL but no solution exist in the net

**Comment by francoischalifour** [comment]
I suggest you to use the [NodeJS driver for MySQL](https://github.com/felixge/node-mysql) to create your API that returns a JSON response for a given route.

You should then be able to use Polymer's [`iron-ajax`](https://github.com/PolymerElements/iron-ajax) element to retrieve the data and inject it to your page via data-binding.

``` html
<iron-ajax
    auto
    url="/api/resource"
    handle-as="json"
    last-response="{{page}}"></iron-ajax>

<h1>[[page.title]]</h1>
<p>[[page.description]]</p>
```

Hope this helps. Good luck with your app!

**Comment by lamjar** [comment]
thank you :+1:
